title: Tabbed Cards
views:
  - title: Map First
    cards:
      - type: custom:tabbed-card
        options:
          defaultCardIndex: 0
        styles:
        tabs:
          - label: Map Tab
            card:
              type: map
              title: Map
              entities:
                - device_tracker.demo_paulus
                - device_tracker.demo_anne_therese
          - label: Grid
            card:
              type: grid
              square: false
              columns: 1
              cards:
                - type: humidifier
                  entity: humidifier.dehumidifier
                - type: humidifier
                  entity: humidifier.humidifier
                - type: humidifier
                  entity: humidifier.hygrostat
          - label: Button
            card:
              type: button
              entity: light.bed_light
              tap_action:
                action: toggle
              show_name: true
              show_icon: true
              show_state: true
  - title: Map Second
    cards:
      - type: custom:tabbed-card
        options:
          defaultCardIndex: 0
        tabs:
          - label: Grid
            card:
              type: grid
              square: false
              columns: 1
              cards:
                - type: humidifier
                  entity: humidifier.dehumidifier
                - type: humidifier
                  entity: humidifier.humidifier
                - type: humidifier
                  entity: humidifier.hygrostat
          - label: Map Tab
            card:
              type: map
              title: Map
              entities:
                - device_tracker.demo_paulus
                - device_tracker.demo_anne_therese
          - label: Button
            card:
              type: button
              entity: light.bed_light
              tap_action:
                action: toggle
              show_name: true
              show_icon: true
              show_state: true
  - title: Solo
    cards:
      - type: custom:tabbed-card
        options:
          defaultCardIndex: 0
        tabs:
          - label: Grid
            card:
              type: grid
              square: false
              columns: 1
              cards:
                - type: humidifier
                  entity: humidifier.dehumidifier
                - type: humidifier
                  entity: humidifier.humidifier
                - type: humidifier
                  entity: humidifier.hygrostat
          - label: Test Map
            card:
              type: map
              title: Test Map
              entities:
                - device_tracker.demo_paulus
                - device_tracker.demo_anne_therese
          - label: Thermostat
            card:
              type: thermostat
              name: HVACS
              entity: climate.hvac
          - label: button
            card:
              type: button
              entity: light.bed_light
              tap_action:
                action: toggle
              show_name: true
              show_icon: true
              show_state: true
          - label: Sensors
            card:
              type: entities
              title: Sensor
              entities:
                - sensor.carbon_dioxide
                - sensor.carbon_monoxide
                - sensor.outside_humidity
                - sensor.outside_temperature
                - sensor.power_consumption
                - sensor.today_energy
          - label: Air Quality
            card:
              type: entities
              title: Air Quality
              entities:
                - air_quality.demo_air_quality_home
                - air_quality.demo_air_quality_office
          - label: Lights
            card:
              type: entities
              title: Light
              entities:
                - light.bed_light
                - light.ceiling_lights
                - light.entrance_color_white_lights
                - light.kitchen_lights
                - light.living_room_rgbww_lights
                - light.office_rgbw_lights
          - label: Binary Sensor
            card:
              type: entities
              title: Binary sensor
              entities:
                - binary_sensor.basement_floor_wet
                - binary_sensor.movement_backyard
          - label: Calendar
            card:
              type: entities
              title: Calendar
              entities:
                - entity: calendar.calendar_1
                  name: "1"
                - entity: calendar.calendar_2
                  name: "2"
          - label: Grid
            card:
              type: grid
              square: false
              columns: 1
              cards:
                - type: picture-entity
                  entity: camera.demo_camera
                - type: thermostat
                  name: HVACS
                  entity: climate.hvac
                - type: entities
                  title: Calendar
                  entities:
                    - entity: calendar.calendar_1
                      name: "1"
                    - entity: calendar.calendar_2
                      name: "2"
                - type: picture-entity
                  entity: camera.demo_camera_png
  - title: Many
    cards:
      - type: entities
        title: Air Quality
        entities:
          - air_quality.demo_air_quality_home
          - air_quality.demo_air_quality_office
      - type: custom:tabbed-card
        options:
          defaultCardIndex: 0
        tabs:
          - label: Test Map
            card:
              type: map
              title: Test Map
              entities:
                - device_tracker.demo_paulus
                - device_tracker.demo_anne_therese
          - label: Grid
            card:
              type: grid
              square: false
              columns: 1
              cards:
                - type: humidifier
                  entity: humidifier.dehumidifier
                - type: humidifier
                  entity: humidifier.humidifier
                - type: humidifier
                  entity: humidifier.hygrostat
          - label: Thermostat
            card:
              type: thermostat
              name: HVACS
              entity: climate.hvac
          - label: button
            card:
              type: button
              entity: light.bed_light
              tap_action:
                action: toggle
              show_name: true
              show_icon: true
              show_state: true
          - label: Sensors
            card:
              type: entities
              title: Sensor
              entities:
                - sensor.carbon_dioxide
                - sensor.carbon_monoxide
                - sensor.outside_humidity
                - sensor.outside_temperature
                - sensor.power_consumption
                - sensor.today_energy
          - label: Air Quality
            card:
              type: entities
              title: Air Quality
              entities:
                - air_quality.demo_air_quality_home
                - air_quality.demo_air_quality_office
          - label: Lights
            card:
              type: entities
              title: Light
              entities:
                - light.bed_light
                - light.ceiling_lights
                - light.entrance_color_white_lights
                - light.kitchen_lights
                - light.living_room_rgbww_lights
                - light.office_rgbw_lights
          - label: Binary Sensor
            card:
              type: entities
              title: Binary sensor
              entities:
                - binary_sensor.basement_floor_wet
                - binary_sensor.movement_backyard
          - label: Calendar
            card:
              type: entities
              title: Calendar
              entities:
                - entity: calendar.calendar_1
                  name: "1"
                - entity: calendar.calendar_2
                  name: "2"
          - label: Grid
            card:
              type: grid
              square: false
              columns: 1
              cards:
                - type: entities
                  title: Button
                  entities:
                    - button.push
                - type: picture-entity
                  entity: camera.demo_camera
                - type: picture-entity
                  entity: camera.demo_camera_png
      - type: entities
        title: Button
        entities:
          - button.push
      - type: alarm-panel
        entity: alarm_control_panel.security
  - title: Styled
    cards:
      - type: custom:tabbed-card
        options:
          defaultCardIndex: 0
        styles:
          --mdc-theme-primary: yellow
          --mdc-tab-text-label-color-default: orange
          --mdc-tab-color-default: orange
        attributes:
          label: Global Label
          icon: mdi:stop
          indicatorIcon:
          isFadingIndicator:
          minWidth:
          isMinWidthIndicator:
          stacked:
          active:
        tabs:
          - styles:
              --mdc-theme-primary: green
              --mdc-tab-text-label-color-default: pink
              --mdc-tab-color-default: pink
            attributes:
              label: Button
              icon: mdi:fire
              indicatorIcon:
              isFadingIndicator:
              minWidth:
              isMinWidthIndicator:
              stacked:
              active:
            card:
              type: button
              entity: light.bed_light
              tap_action:
                action: toggle
              show_name: true
              show_icon: true
              show_state: true
          - attributes:
              label: Sensors
              icon: mdi:tree
              indicatorIcon:
              isFadingIndicator:
              minWidth:
              isMinWidthIndicator:
              stacked:
              active:
            card:
              type: entities
              title: Sensor
              entities:
                - sensor.carbon_dioxide
                - sensor.carbon_monoxide
                - sensor.outside_humidity
                - sensor.outside_temperature
                - sensor.power_consumption
                - sensor.today_energy
          - attributes:
              label: Air Quality
              icon: mdi:play
              indicatorIcon:
              isFadingIndicator:
              minWidth:
              isMinWidthIndicator:
              stacked:
            card:
              type: entities
              title: Air Quality
              entities:
                - air_quality.demo_air_quality_home
                - air_quality.demo_air_quality_office
          - card:
              type: entities
              title: Binary sensor
              entities:
                - binary_sensor.basement_floor_wet
                - binary_sensor.movement_backyard
# Example dashboard configuration
# title: Tabbed Cards
# views:
#   - title: tabbed-card
#     cards:
#       - type: custom:tabbed-card
#         entities:
#           - light.bed_light
#           - switch.decorative_lights
# views:
#   title: Tabbed-Cards
#   # name: Example
#   cards:
#     - type: custom:tabbed-card
#       entities:
#         # - input_boolean.switch_ac_kitchen
#         # - input_boolean.switch_ac_livingroom
#         # - input_boolean.switch_tv
#         # - input_boolean.switch.ac
#         # - light.bed_light
#################################
# title: My Awesome Home
# views:
#     # View tab title.
#   - title: Example
#     # The cards to show on this view.
#     cards:
#         # The filter card will filter entities for their state
#       - type: entity-filter
#         entities:
#           - device_tracker.paulus
#           - device_tracker.anne_there
#         state_filter:
#           - 'home'
#         card:
#           type: glance
#           title: People that are home

#         # The picture entity card will represent an entity with a picture
#       - type: picture-entity
#         image: https://www.home-assistant.io/images/default-social.png
#         entity: light.bed_light

#     # Specify a tab icon if you want the view tab to be an icon.
#   - icon: mdi:home-assistant
#     # Title of the view. Will be used as the tooltip for tab icon
#     title: Second view
#     cards:
#         # Entities card will take a list of entities and show their state.
#       - type: entities
#         # Title of the entities card
#         title: Example
#         # The entities here will be shown in the same order as specified.
#         # Each entry is an entity ID or a map with extra options.
#         entities:
#           - light.kitchen
#           - switch.ac
#           - entity: light.living_room
#             # Override the name to use
#             name: LR Lights

#         # The markdown card will render markdown text.
#       - type: markdown
#         title: Dashboard
#         content: >
#           Welcome to your **dashboard**.
